### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by selamisozer** [masweetman/issue_charts#23] opened 2017-06-11 10:49 UTC
Error loading chart 'Grafik'. undefined method `line_chart' for #<#:0x49c6dd0>

**Comment by masweetman** [comment] 2017-06-11 13:00
Duplicate of issue #21. Try running bundle update.

**Closed by masweetman** 2017-06-11 13:00 UTC

**Comment by selamisozer** [comment] 2017-06-11 17:32
Hi,
My problem continues :(
Error loading chart 'Grafik'. undefined method `column_chart' for #<#:0x9bfc298>
